"""add_annotation_review_export

Revision ID: d42a541ee3e9
Revises: 45ee41e5644d
Create Date: 2026-05-01 16:04:17.595793+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'd42a541ee3e9'
down_revision: Union[str, None] = '45ee41e5644d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('exported_by', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('JSON', 'JSONL', 'CSV', name='export_format', create_constraint=True), nullable=False),
    sa.Column('filter_status', sa.Enum('APPROVED_ONLY', 'ALL', name='export_filter_status', create_constraint=True), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.create_table('annotation_drafts',
    sa.Column('task_sample_id', sa.UUID(), nullable=False),
    sa.Column('draft_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_sample_id'], ['task_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_drafts_task_sample_id'), 'annotation_drafts', ['task_sample_id'], unique=True)
    op.create_table('annotations',
    sa.Column('task_sample_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.String(length=5000), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_sample_id'], ['task_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_task_sample_id'), 'annotations', ['task_sample_id'], unique=False)
    op.create_table('reviews',
    sa.Column('task_sample_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Enum('APPROVED', 'REJECTED', name='review_result', create_constraint=True), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_sample_id'], ['task_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_task_sample_id'), 'reviews', ['task_sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_task_sample_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_annotations_task_sample_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_annotation_drafts_task_sample_id'), table_name='annotation_drafts')
    op.drop_table('annotation_drafts')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_table('exports')
    # ### end Alembic commands ###
